server:
  port: 8080

token:
  secret: DZyGYXvH/pjHhyQbw8TIE+xNN8PA12yqW4n5Ah0kGQiOa4t/kdWIC9EV40Ymnd/z1ALADdFZT/Yt6R5AJOJ/gA=="
  expiration_time: 86400000  # 1? (??? ??)
spring:
  application:
    name: DDIS_Project

  security:
    user:
      name: none
      password: none

  ## jpa config
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        '[format_sql]': true

  ## redis 설정
  data:
    redis:
      host: localhost
      port: 6379

  ## SMTP 설정
  mail:
    host: smtp.gmail.com
    port: 587
    username:
    password:
    properties:
      mail:
        smtp:
          auth: true
          starttls:                               # SMTP 서버가 TLS를 사용하여 안전한 연결을 요구하는 경우 true로 설정한다.
            enable: true                          # 클라이언트가 SMTP 서버와의 연결을 설정하는 데 대기해야 하는 시간(Millisecond)
            required: true                        # 클라이언트가 SMTP 서버로부터 응답을 대기해야 하는 시간(Millisecond).
          connection timeout: 5000
          timeout: 5000
          write timeout: 5000                     # 클라이언트가 작업을 완료하는데 대기해야 하는 시간(Millisecond).
      auth-code-expiration-millis: 1800000        # 이메일 인증 코드의 만료 시간(Millisecond)


  datasource:
    driver-class-name: org.mariadb.jdbc.Driver

    url: jdbc:mariadb://localhost:3307/     #각자 수정
    username: root                                #각자 수정
    password: mariadb                                #각자 수정

